### ISSUE TITLE
Comment regarding the cons of solution 3

### ISSUE THREAD

**Issue by moufmouf** [Giuseppe-Mazzapica/container-interop-experiments#1]
Hey Giuseppe,

I've just had a proper look to the work you have been doing here. Congrats! That's a huge amount of work :)

Here is a quick comment. Regarding solution 3, you say:

> there's no way to enforce the signature of factory callbacks (at least with current versions of PHP). It means that implementation details are not recognizable just from code, but implementers are required to read documentation to implement this standard. It also means that it the implementation is not "type safe".

This is absolutely true. But you seem to imply that solution 2 is more type-safe in that regard.

However, solution 2 is not more type-safe than solution 3 since even in PHP 7, the best return type you can get is `array`. So the `serviceFactories()` cannot be trusted to return an array of `ServiceFactoryInterface`. We are dealing with the limitations of PHP here.

So most of your drawback in solution 3 also applies to solution 2. I'd put something like this:

> there's no way to enforce the array returned by the `serviceFactories()` is an array of `ServiceFactoryInterface` (at least with current versions of PHP). It means that implementation details are not recognizable just from code, but implementers are required to read documentation to implement this standard. It also means that it the implementation is not "type safe".

Since PHP cannot really offer type safety, I'd definitely favor solution 3 that is way easier, as it doesn't require a new class for each factory.

**Comment by gmazzap** [comment]
Hi @moufmouf thanks for your comment.

> However, solution 2 is not more type-safe than solution 3 since even in PHP 7, the best return type you can get is array. So the serviceFactories() cannot be trusted to return an array of...

Yes, you can't trust `serviceFactories()` about the type of array item because of PHP limits (as of current versions). However, as you can see in my implementation, I implemented this in the container with a simple:

``` php
$container = new Container();
$providers = [new AppServiceProvider()];
array_walk($providers, [$container, 'useProvider']);
```

_([source](https://github.com/Giuseppe-Mazzapica/container-interop-experiments/blob/master/experiment-02/index.php#L21-L22))_

And the method `Container::useProvider()` can enforce the type of every element via [type hint](https://github.com/Giuseppe-Mazzapica/container-interop-experiments/blob/master/experiment-02/src/Container.php#L67).

Surely this apply to solution 3 as well. The problem is that in the solution 3 you can only enforce the type `callable` and (in current versions of PHP) there's no way to trust a callable about the type it accepts, you can just call it and "hope" it is the right kind of callable.

In solution 2, the type enforced is `ServiceFactoryInterface` which can enforce the signature of its  [`factory()` method](https://github.com/Giuseppe-Mazzapica/container-interop-experiments/blob/master/experiment-02/src/ServiceFactoryInterface.php#L33).

This is why I said that method 2 is more type-safe than method 3. However, I have to say that the fact that method 2 needs a factory object for each service looks overwhelming to me, this is why I think that, even if less "safe", solution 3 is a better trade off... waiting that one of the current RFCs that could enforce signature of a callable (I counted 3 of them) will be merged in PHP.

**Comment by moufmouf** [comment]
:+1:
